### ISSUE TITLE
[BUG] - Improper Media Playback Size

### ISSUE THREAD

**Issue by Saccadence** [Knewest/uncompressed-discord-images#10]
**Describe the bug:**
Video files that are played from discord media links improperly size themselves in playback.

**How to reproduce:**
Steps to reproduce the behaviour:
1. Go to an uploaded video file
2. Click on it to begin playback
3. See error

**Expected behaviour:**
Video playback should begin and not be cropped, leaving a portion incapable of being viewed.

**Screenshots:**
![Screenshot_100](https://github.com/Knewest/uncompressed-discord-images/assets/82685068/2c516f02-e910-422b-ad30-ee2da36eec4b)
![Screenshot_101](https://github.com/Knewest/uncompressed-discord-images/assets/82685068/be306b85-fdaa-41f5-8d4d-95f399111032)

**Version of Discord:**
Regular Discord:
Stable 202828 (8ea2bc1) 
Host 1.0.9013 (32266) 
Windows 10 64-Bit (10.0.19045)

**Additional context:**
I've also attached an image of the plugins that I have added to Better Discord.
![Screenshot_102](https://github.com/Knewest/uncompressed-discord-images/assets/82685068/3de1f3e5-5ff2-4b12-9dc5-e4850344006c)

**Comment by Saccadence** [comment]
Forgot to mention that I have confirmed the change in functionality comes from the direct enabling and disabling of only the Uncompressed Images plugin. However, I'm unaware of whether or not there is some interference from other plugins or not that may be affecting the functionality.

**Comment by Knewest** [comment]
The issue has been found as a conflict with the plugin [QuickView](https://betterdiscord.app/plugin/QuickView) by [Qwerasd](https://betterdiscord.app/developer/Qwerasd) (as per discussion in the BetterDiscord server).<br>This issue will be addressed in v3.12, thank you for your issue report.
