### ISSUE TITLE
[FEATURE RQST] - Add "?quality=lossless" to the end of profile picture image urls

### ISSUE THREAD

**Issue by kolatez** [Knewest/uncompressed-discord-images#12]
**Is your feature request related to a problem? Please describe.**
Discord compresses profile picture images, streaming a low quality version to browser and desktop users and a somewhat higher quality version to mobile users.

**Describe the solution you'd like**
For urls containing cdn.discordapp.com/avatars, add ?quality=lossless to the end to provide a higher quality image to view in the client.

**Additional context**
Mobile users actually view profile pictures with lossless quality by default

Browser and desktop users get to see this:

https://cdn.discordapp.com/avatars/348163446896066561/eaa5612c1a07cdd55f9d31c6eaac870f.webp

Mobile users get to see this:

https://cdn.discordapp.com/avatars/348163446896066561/eaa5612c1a07cdd55f9d31c6eaac870f.webp?quality=lossless

**Comment by Knewest** [comment]
I see. When I get home in around three days, I will see what I can do to implement this. 
This extra compression is unnecessary.

**Comment by Knewest** [comment]
UPDATE: My inactivity will be extended to an extra week. Apologies if you need to contact me and I am unreachable.

**Comment by Knewest** [comment]
Feature request has been implemented in v3.14.
