### ISSUE TITLE
Aspect Ratio Glitch

### ISSUE THREAD

**Issue by Morpho-Dee-EX** [Knewest/uncompressed-discord-images#14]
**Describe the bug:**
A video's aspect ratio will display improperly, after playing it.

**How to reproduce:**
Steps to reproduce the behaviour:
1. Send a video.
2. Click on the video. The aspect ratio doesn't change before playing it.
3. Upon playing the video (may take multiple tries) the aspect ratio may stretch, closer to a rectangle.

**Expected behaviour:**
The video should play normally.

**Screenshots:**
![image](https://github.com/Knewest/uncompressed-discord-images/assets/123109858/f832f8f8-0e32-405f-a5e3-74eeafee85ea)
Before clicking.
![image](https://github.com/Knewest/uncompressed-discord-images/assets/123109858/75c0ff00-6a34-4550-a679-0e24f4127150)
After clicking.
![image](https://github.com/Knewest/uncompressed-discord-images/assets/123109858/27b4eb1f-6b7a-4fa3-ac8e-0299ee50f569)
This one has the plugin disabled.

**Version of Discord:**
Regular Discord, version number Stable 252471.

**Comment by Knewest** [comment]
Hi, may you confirm what version of the plugin you are using? This should've been fixed on v3.21 and onwards.

**Comment by Morpho-Dee-EX** [comment]
I was installing through the Plugin Repo plugin, and I now installed the latest version on the GitHub page, the bug is fixed.
