### ISSUE TITLE
[BUG] - Videos resize when hovered while playing

### ISSUE THREAD

**Issue by NoSkillPureAndy** [Knewest/uncompressed-discord-images#15]
**Describe the bug:**
When you play some videos, when you move your mouse around over the message it belongs to it'll resize by a few pixels over and over, restarting it each time.

**How to reproduce:**
Steps to reproduce the behaviour:
1. Send a video
2. Play the video
3. Move your mouse around over the message

**Expected behaviour:**
I'd expect this not to happen and for the video to play normally

**Screenshots:**
[If applicable, add screenshots to help explain your problem.](https://github.com/Knewest/uncompressed-discord-images/assets/72871450/e01c6e9b-8e04-4fb1-8143-d7c74d43780a)

**Version of Discord:**
Stable 252966 (b583bea)

**Additional context:**
Not all videos resize like this and cause a chain reaction of restarting, but all videos restart when you initially hover over.

**Comment by Knewest** [comment]
Hi, does this happen when you have ImageUtilities by DevilBro enabled? There is currently a bug with that plugin that does exactly what you are reporting.

**Comment by NoSkillPureAndy** [comment]
Disabled it and the issue was fixed.
