### ISSUE TITLE
question concerning : https://github.com/Knewest/precompiled-jxrlib-binaries because there is no 'issues' tab on this repository

### ISSUE THREAD

**Issue by ACIXCIX0001** [Knewest/uncompressed-discord-images#16]
morning !

starred your 'https://github.com/Knewest/precompiled-jxrlib-binaries' yesterday !

tried :
```
'JxrDecApp.exe -i 'Screenshot 2023-12-19 14-28-03_test_hdr_original.jxr' -o 'Screenshot 2023-12-19 14-28-03_test_hdr_jxrdecapp.tif'
`JxrEncApp.exe -i ''Screenshot 2023-12-19 14-28-03_test_hdr_jxrdecapp.tif' -o 'Screenshot 2023-12-19 14-28-03_test_hdr_jxrencapp.jxr'
```
the issue is that `'JxrEncApp.exe -i 'Screenshot 2023-12-19 14-28-03_test_hdr_original.jxr'` is 16 bits per color image when converting it to .tiff then back to .jxr, the image is still 16 bpc according to imagemagick
```
magick identify -verbose 'Screenshot 2023-12-19 14-28-03_test_hdr_jxrencapp.jxr'
```
however it s obvious that something happened during the 1st loading then converting of the .jxr image, most probably that JxrEncApp.exe 1st converted the original 16 bpc image to 8 bpc then re encapsulate it in the .tif container as a 32 bpc imagehence from an 8 bpc source then converted this image back to .jxr in a 16 bpc container but still with the bit depth loss.
if you then open the resulting image with [windows photo app, hdr + wcg image viewer], you will clearly notice the bit depth loss by the blown out highlights and burnt colors.
aware that you did not wrote the software and that is just a binary compilation for windows to .exe from the original microsoft 'https://github.com/4creators/jxrlib' repository but, do you manage to convert [nvidiashadowplay, obs] .jxr screenshots to [.tif, .exr, .hdr, .jxr] without loosing the original 16 bpc depth information when opening it back with [windows photo app, hdr + wcg image viewer] ?
if no do you know a way to do it properly ?

'https://1drv.ms/f/s!AiUmCeW6ezhq9yl2dNVv5Vm1SLxg'

**Comment by Knewest** [comment]
Hi, try specifying the bit depth.

### Example:
```cmd
JXRDecApp.exe -i "Screenshot 2023-12-19 14-28-03_test_hdr_original.jxr" -o "Screenshot 2023-12-19 14-28-03_test_hdr_jxrdecapp.tif" -c 10
```

### Relevant list:
```cmd
 -c format                    Specifies the uncompressed output format
                               0: 24bppBGR
                               1: 1bppBlackWhite
                               2: 8bppGray
                               3: 16bppGray
                               4: 16bppGrayFixedPoint
                               5: 16bppGrayHalf
                               7: 32bppGrayFixedPoint
                               8: 32bppGrayFloat
                               9: 24bppRGB
                              10: 48bppRGB
                              11: 48bppRGBFixedPoint
                              12: 48bppRGBHalf
                              14: 96bppRGBFixedPoint
                              15: 128bppRGBFloat
                              16: 32bppRGBE
                              17: 32bppCMYK
                              18: 64bppCMYK
                              22: 32bppBGRA
                              23: 64bppRGBA
                              24: 64bppRGBAFixedPoint
                              25: 64bppRGBAHalf
                              27: 128bppRGBAFixedPoint
                              28: 128bppRGBAFloat
                              29: 16bppBGR555
                              30: 16bppBGR565
                              31: 32bppBGR101010
                              32: 40bppCMYKA
                              33: 80bppCMYKA
                              34: 32bppBGR
```

### FYI, 48-bpp (bits per pixel) is equal to 16-bpc (bits per channel):
```cmd
Total bpp = bpc × number of channels
Total bpp = 16-bpc × 3 channels
Total bpp = 48-bpp
```

Additionally, you can investigate other options simply by entering the binary executable in the correct directory with nothing else to display a list of options.

Hope this helps.
Knew.

**Comment by ACIXCIX0001** [comment]
thank for your answer !
re tried and apparently jxrdecapp does it s job, but the image has to be converted back to .jxr with jxrencapp for [windows photo app, hdr + wcg photo viewer], to display the data in hdr, .tif directly is all dull and washed out.

**Comment by ACIXCIX0001** [comment]
@Knewest, after multiple tryouts, came to the conclusion that the issue wasn t the bit depth that wasen t kept but actually the rec. 2100 color color space and the st. 2084 pq that wasn t kept.
are you aware of this issue and if jxrlib offers a way to keep this hdr metadata ?
