### ISSUE TITLE
[FEATURE RQST] - somehow fix png to JPEG

### ISSUE THREAD

**Issue by skeddles** [Knewest/uncompressed-discord-images#18]
**Is your feature request related to a problem? Please describe.**
images uploaded as png are converted to jpeg
<img width="205" alt="firefox_2024-03-14_11-07-18" src="https://github.com/Knewest/uncompressed-discord-images/assets/2721332/66dbae7f-ec38-4b52-bd81-7cbddfbf57fc">

**Describe the solution you'd like**
display the original png if possible

**Describe alternatives you've considered**
i tried opening it in the browser and the url says png, but the mimetype says jpeg

**Additional context**

**Comment by Knewest** [comment]
Hey, sorry for the late response. I was busy at the time and forgot till now. The reason this happens is because it is a JPEG with the `*.png` file extension. This behaviour is usually seen on Apple devices.
