### ISSUE TITLE
Images changing too quick, resulting in the chat moving up and then down.

### ISSUE THREAD

**Issue by Knewest** [Knewest/uncompressed-discord-images#3]
![ezgif-1-a295b330b1](https://user-images.githubusercontent.com/94736474/226165546-8a04f85b-c6db-476b-818e-3a76b1a4d31a.gif)

**Comment by Kanzuke117** [comment]
I'm seeing similar behaviour to your gif in 3.2.0, messages with large attachments especially only taking the default line of space until the image starts loading, then suddenly pushing everything above it up. It's most obvious when first switching to the channel
